Project Title: Customer Support Ticket Analyser

 Step 1: Preloaded Tickets
Begin your program with the following dictionary of lists containing 10 customer tickets:

In [2]:
ticket_data = {    'Ticket_No': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Customer_Name': [ 'Ravi', 'Meera', 'Sam', 'Anu', 'Rakesh', 'Divya', 'Arjun', 'Kiran', 'Leela', 'Nisha'
    ],
 'Issue_Description': [
        ' Internet not working!!! ', 'slow response, very poor service ',
        'GREAT support! issue resolved.',' okay... need help ', 'not BAD but slow', 'Excellent guidance, Very Helpful!', 'good support and good behaviour!', 'Poor handling of technical issue', 'Satisfied. Could be better.',  'Good service... quick response.'
    ],
  'Priority': ['High', 'Low', 'High', 'Medium', 'Low', 'High', 'Medium', 'High', 'Low', 'Medium']}
ticket_data

{'Ticket_No': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 'Customer_Name': ['Ravi',
  'Meera',
  'Sam',
  'Anu',
  'Rakesh',
  'Divya',
  'Arjun',
  'Kiran',
  'Leela',
  'Nisha'],
 'Issue_Description': [' Internet not working!!! ',
  'slow response, very poor service ',
  'GREAT support! issue resolved.',
  ' okay... need help ',
  'not BAD but slow',
  'Excellent guidance, Very Helpful!',
  'good support and good behaviour!',
  'Poor handling of technical issue',
  'Satisfied. Could be better.',
  'Good service... quick response.'],
 'Priority': ['High',
  'Low',
  'High',
  'Medium',
  'Low',
  'High',
  'Medium',
  'High',
  'Low',
  'Medium']}

Step 2: Add More Tickets

In [ ]:
next_ticket_num=11
num_tickets=int(input("Enter how many new tickets you want to add?"))
for i in range(num_tickets):
  print(f"/n Entering details for ticket number {next_ticket_num}")
  customer_name=input("Enter customer name: ")
  issue_description=input("Enter issue description: ")

  while True:
        priority=input("Enter ticket priority (High/Medium/Low):").capitalize()
        if priority in ["High","Medium","Low"]:
          break
        else:
          print("Invalid priority! Please enter high, medium or low")

next_ticket_num+=1
ticket_data.append({
        "Ticket No": next_ticket_no,
        "Customer Name": customer_name,
        "Issue_Description": issue_description,
        "Priority": priority
    })


#Display updated ticket details
print("\nUpdated Ticket Data:")
for ticket in ticket_data:
    print(ticket)

In [9]:
import pandas as pd
df=pd.DataFrame(ticket_data)
df

   Ticket_No Customer_Name                  Issue_Description Priority
0          1          Ravi           Internet not working!!!      High
1          2         Meera  slow response, very poor service       Low
2          3           Sam     GREAT support! issue resolved.     High
3          4           Anu                 okay... need help    Medium
4          5        Rakesh                   not BAD but slow      Low
5          6         Divya  Excellent guidance, Very Helpful!     High
6          7         Arjun   good support and good behaviour!   Medium
7          8         Kiran   Poor handling of technical issue     High
8          9         Leela        Satisfied. Could be better.      Low
9         10         Nisha    Good service... quick response.   Medium

In [ ]:
df["Issue_Description"]=df["Issue_Description"].replace("okay","ok")
df

   Ticket_No Customer_Name  Issue_Description Priority
0          1          Ravi                NaN     High
1          2         Meera                NaN      Low
2          3           Sam                NaN     High
3          4           Anu                NaN   Medium
4          5        Rakesh                NaN      Low
5          6         Divya                NaN     High
6          7         Arjun                NaN   Medium
7          8         Kiran                NaN     High
8          9         Leela                NaN      Low
9         10         Nisha                NaN   Medium

Step 3: Text Cleaning for Issue Descriptions

In [ ]:
df["Issue_Description"]=df["Issue_Description"].str.lower()
df["Issue_Description"]=df["Issue_Description"].str.strip()
df["Issue_Description"]=df["Issue_Description"].str.replace("!","")
df["Issue_Description"]=df["Issue_Description"].str.replace(".","")
df

   Ticket_No Customer_Name                 Issue_Description Priority
0          1          Ravi              internet not working     High
1          2         Meera  slow response, very poor service      Low
2          3           Sam      great support issue resolved     High
3          4           Anu                    okay need help   Medium
4          5        Rakesh                  not bad but slow      Low
5          6         Divya  excellent guidance, very helpful     High
6          7         Arjun   good support and good behaviour   Medium
7          8         Kiran  poor handling of technical issue     High
8          9         Leela         satisfied could be better      Low
9         10         Nisha       good service quick response   Medium

 Step 4: Keyword-Based Issue Insights

In [ ]:
def count_tickets_with_word(word):
  count=0
  word= word.lower()

  for desc in df["Issue_Description"]:
    if word in desc:
      count+=1
  return count

In [ ]:
print("Tickets containing 'poor':", count_tickets_with_word("poor"))
print("Tickets containing 'good':", count_tickets_with_word("good"))
print("Tickets containing 'slow':", count_tickets_with_word("slow"))
print("Tickets containing 'excellent':", count_tickets_with_word("excellent"))

Tickets containing 'poor': 2
Tickets containing 'good': 2
Tickets containing 'slow': 2
Tickets containing 'excellent': 1

Step 5: Final Summary & Insights

In [ ]:
ticket_data

{'Ticket_No': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 'Customer_Name': ['Ravi',
  'Meera',
  'Sam',
  'Anu',
  'Rakesh',
  'Divya',
  'Arjun',
  'Kiran',
  'Leela',
  'Nisha'],
 'Issue_Description': [' Internet not working!!! ',
  'slow response, very poor service ',
  'GREAT support! issue resolved.',
  ' okay... need help ',
  'not BAD but slow',
  'Excellent guidance, Very Helpful!',
  'good support and good behaviour!',
  'Poor handling of technical issue',
  'Satisfied. Could be better.',
  'Good service... quick response.'],
 'Priority': ['High',
  'Low',
  'High',
  'Medium',
  'Low',
  'High',
  'Medium',
  'High',
  'Low',
  'Medium']}

2.	Priority Analysis
Compute:
●	Number of High-priority tickets
●	Number of Medium priority tickets
●	Number of Low-Priority tickets

In [5]:
print("\nPriority Analysis:")
print("Number of High-priority tickets:",
      sum(ticket_data["Priority"] == "High" for ticket in ticket_data))

print("Number of Medium-priority tickets:",
      sum(ticket_data["Priority"] == "Medium" for ticket in ticket_data))

print("Number of Low-priority tickets:",
      sum(ticket_data["Priority"] == "Low" for ticket in ticket_data))

Priority Analysis:
Number of High-priority tickets: 0
Number of Medium-priority tickets: 0
Number of Low-priority tickets: 0

3.	Find the Ticket With the Longest Issue Description
Based on word count, print:
●	Ticket number
●	Customer name
●	Cleaned issue text
●	Word count

In [12]:
longest_ticket = df.assign(
    Word_Count=df["Issue_Description"].str.split().str.len()
).loc[lambda x: x["Word_Count"].idxmax()]

print("\nTicket With Longest Issue Description:\n")

print("Ticket Number:", longest_ticket["Ticket_No"])
print("Customer Name:", longest_ticket["Customer_Name"])
print("Cleaned Issue Text:", longest_ticket["Issue_Description"])
print("Word Count:", longest_ticket["Word_Count"])

Ticket With Longest Issue Description:

Ticket Number: 2
Customer Name: Meera
Cleaned Issue Text: slow response, very poor service
Word Count: 5

4.	Extract Unique Words Used
Generate a set of all unique words across all issue descriptions.
Show:
●	Count of unique words
●	The word list (sorted)

In [19]:
# Combine all issue descriptions into one string
all_text = " ".join(df["Issue_Description"].astype(str))

# Convert to lowercase and split into words
words = all_text.lower().split()

# Create a set of unique words
unique_words = set(words)

# Sort the words
sorted_unique_words = sorted(unique_words)

print("Count of unique words:", len(sorted_unique_words))
print("\nList of unique words:")
print(sorted_unique_words)

Count of unique words: 34

List of unique words:
['and', 'bad', 'be', 'behaviour!', 'better.', 'but', 'could', 'excellent', 'good', 'great', 'guidance,', 'handling', 'help', 'helpful!', 'internet', 'issue', 'need', 'not', 'of', 'okay...', 'poor', 'quick', 'resolved.', 'response,', 'response.', 'satisfied.', 'service', 'service...', 'slow', 'support', 'support!', 'technical', 'very', 'working!!!']